---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site-xfusion
  namespace: jekyll-namespace-xfusion
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: jekyll-pod-xfusion
  namespace: jekyll-namespace-xfusion
  labels:
    app: jeykll
spec:
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site-xfusion
  initContainers:
  - name: jekyll-init-xfusion
    image: kodekloud/jekyll
    imagePullPolicy: IfNotPresent
    command: [ "jekyll", "new", "/site" ] 
    volumeMounts:
      - name: site
        mountPath: /site
  containers:
  - name: jekyll-container-xfusion
    image: kodekloud/jekyll-serve
    volumeMounts:
      - name: site
        mountPath: /site
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jeykll
  name: jekyll-container-xfusion
  namespace: jekyll-namespace-xfusion
spec:
  selector:
    app: jeykll
  type: NodePort
  ports:
  - port: 8080
    targetPort: 4000
    nodePort: 31181
    protocol: TCP
status:
  loadBalancer: {}