apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-xfusion
  namespace: grafana-monitoring-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container-xfusion
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
      volumes:
        - name: grafana-storage
          emptyDir: {}
      
-------------------------------------------------------------------------

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-xfusion
  namespace: grafana-monitoring-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
  spec:
    containers:
    - name: grafana-container-xfusion
      image: grafana/grafana:latest
      ports:
      - containerPort: 3000
    resources: 
      limits:
        memory: "2Gi"
        cpu: "1000m"
      requests: 
        memory: "1Gi"
        cpu: "500m"
   volumeMounts:
      - name: grafana-storage
        mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        emptyDir: {}