apiVersion: v1
kind: Pod
metadata:
  labels: 
  name: webserver
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts: 
    - name: shared-logs
      mountPath: /var/log/nginx
  - name: sidecar-container
    image: ubuntu:latest
    command: [ "/bin/sh", "-c" ] 
    args: [ "while true; do (cat /var/log/nginx/access.log) && (cat /var/log/nginx/access.log); sleep 30; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    