apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-namespace-devops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-devops
  namespace: tomcat-namespace-devops
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container-devops
        image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
        ports:
        - name: tomcat
          containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat
  name: tomcat-service-devops
  namespace: tomcat-namespace-devops
spec:
  selector:
    app: tomcat
  ports:
  - name: port-tomcat
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32227
  type: nodePort
