apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xfusion
spec:
  schedule: "*/7 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-xfusion
            image: httpd:latest
            args:
            - /bin/sh
            - -c
            - echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
------------------

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datacenter
spec:
  schedule: "*/9 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-datacenter
              image: httpd:latest
              command:
                - /bin/sh
                - -c
                - echo "Welcome to xfusioncorp!"
          restartPolicy: OnFailure