  
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
  labels:
    name: db-service
    app: demo-voting-app
spec:
  ports:
  type: ClusterIP
  - port: 5432
    targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app
