apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app-deploy
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-deploy
  template:
    metadata:
      labels:
        app: node-app-deploy
    spec:
      containers:
        - name: node-container-deploy
          image: gcr.io/kodekloud/centos-ssh-enabled:node
          ports:
            - containerPort: 80